name = "private-photo"
compatibility_date = "2024-08-01"
compatibility_flags = [ "nodejs_compat" ]
node_compat = true  # 显式启用完整Node.js兼容模式

# 动态R2存储桶绑定（通过环境变量配置）
[[unsafe.bindings]]
name = "R2"
type = "r2_bucket"
bucket_name = ""  # 完全动态绑定

# KV 命名空间绑定（用于速率限制）
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "RATE_LIMIT_KV_ID"

# 环境变量
[vars]
JWT_SECRET = "请在此处设置一个强密钥"  # 通过Cloudflare Dashboard设置实际值
MAX_FILE_SIZE_BYTES = "52428800"  # 50MB
ALLOWED_FILE_TYPES = "image/*,video/mp4"