name = "private-photo"
compatibility_date = "2024-08-01"
compatibility_flags = [ "nodejs_compat" ]
node_compat = true  # 显式启用完整Node.js兼容模式

# R2存储桶绑定（必需）
[[r2_buckets]]
binding = "R2"  # 必须与代码中的env.R2对应
bucket_name = "test"  # 需先在Cloudflare控制台创建

# KV 命名空间绑定（用于速率限制）
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "RATE_LIMIT_KV_ID"

# 环境变量
[vars]
JWT_SECRET = "请在此处设置一个强密钥"  # 通过Cloudflare Dashboard设置实际值
MAX_FILE_SIZE_BYTES = "52428800"  # 50MB
ALLOWED_FILE_TYPES = "image/*,video/mp4"